name: CTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake --build ./build/Release
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: >
          cmake --build ./build/Release
          -j $(grep -c 'processor' /proc/cpuinfo)
          -t er_gen tests

      - name: Test
        working-directory: ./build/Release
        run: ctest --rerun-failed --output-on-failure
